[#119] 모임 내의 피드 생성 API 마이그레이션 & 알림 붙이기
sopt-makers/sopt-crew-backend pull request #124
Opened 2024-02-02 08:15 UTC by yeseul106

## 👩‍💻 Contents

- 모임 내의 피드 생성하는 API 마이그레이션 작업 했습니다.
 - 내가 속한 모임에 피드 글 생성되면 푸시 알림 보내도록 알림 붙이는 작업까지 구현해봤습니다. 
    구조를 제가 잡긴 했는데, 더 나은 구조가 있다면 편하게 말씀해주세요..! 다음 API 부터 반영해보도록 하겠습니다 !

## 📝 Review Note

- 에러 케이스가 세부적으로 나뉘는 API(모임이 없어요, 권한이 없어요 등..?)라서 에러 발생했을 때 response body에 기존 nest.js에서 내려줬던 메세지값 똑같이 내려주도록 구현했습니다.
    - 요거 은수오빠랑 슬랙으로 커스텀 에러 코드 주는 걸로 이야기 했었던거 같은데, 일단은 메세지 자체를 내려주도록 했어요. 다시 한번 논의를 해봐야 할 거 같긴 합니다 ! 
 - 논의해보고 싶은 또 다른 한가지는, 알림 서버에 요청을 했는데 response로 400이나 500이 왔을 경우, 저희 어플리케이션 단에서 어떻게 에러 처리를 할지 정해보면 좋을 것 같습니다 👀

## 📣 Related Issue

- closed #119

2024-02-02 12:33 UTC, rdd9223 requested changes
코드 보면서 많이 배웁니다!! 한번 확인 부탁드려요!

2024-02-02 12:33 UTC, rdd9223 commented on main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
main 디렉토리 하위에 external에 넣어두셨는데, 조금 의미가 다르지 않을까 싶어서 언급드립니다!
제가 생각한 external은 메이커스외의 API호출이에요. 예를 들면 구글 로그인 API, 카페24등의 메시징 서비스 API 등
그래서 알림 API의 경우 메이커스(회사)내 호출이므로 internal이 조금 더 적합한 디렉토리 명이 아닐까 생각이 듭니다!

2024-02-02 12:33 UTC, rdd9223 commented on main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
> +  private static final String NEW_POST_PUSH_NOTIFICATION_TITLE = "✏️내 모임에 새로운 글이 업로드됐어요.";
알림에 관한 Constant / Enum들은 notification 패키지 안에서 관리하도록 하면 조금 더 코드가 응집성 있을 것 같아요!

2024-02-02 12:33 UTC, rdd9223 commented on main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
> +   * 모임 게시글 작성 - 모임에 속한 유저만 작성 가능 - 모임에 속한 유저가 아니면 403 에러
주석을 JavaDoc 문법을 이용해서 더 명확하게 작성할 수 있을 것 같아요!
```java
/**
 * 모임 게시글 작성
 * @apiNote 모임에 속한 유저만 작성 가능
 * @throws 403 모임에 속한 유저가 아닌 경우
*/
```

2024-02-02 12:36 UTC, rdd9223 commented
> 에러 케이스가 세부적으로 나뉘는 API(모임이 없어요, 권한이 없어요 등..?)라서 에러 발생했을 때 response body에 기존 nest.js에서 내려줬던 메세지값 똑같이 내려주도록 구현했습니다.
요거 은수오빠랑 슬랙으로 커스텀 에러 코드 주는 걸로 이야기 했었던거 같은데, 일단은 메세지 자체를 내려주도록 했어요. 다시 한번 논의를 해봐야 할 거 같긴 합니다 !

요건 슬랙에서도 언급 드렸듯이 우선 메시지값 똑같이 내려주고 추후 개선이 필요할 것 같아요!

> 논의해보고 싶은 또 다른 한가지는, 알림 서버에 요청을 했는데 response로 400이나 500이 왔을 경우, 저희 어플리케이션 단에서 어떻게 에러 처리를 할지 정해보면 좋을 것 같습니다 👀

그냥 처리하지 않으면 될 것 같아요. 비즈니스 로직과 알림 전송 기능은 원자적으로 가져가고, 알림 실패의 경우에는 알림 API에서 실패알림 파악 및 재전송 처리까지의 수복기능이 있어야할 것 같아요. 각 서비스 서버에서는 책임지지 않는 것으로!

2024-02-03 09:23 UTC, yeseul106 reviewed
좋은 피드백 너무 감사합니다 !!! 리뷰 반영해서 push 하겠습니다앗 !

2024-02-03 09:23 UTC, yeseul106 commented on main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
> +  List<Apply> findAllByMeetingIdAndStatus(Integer meetingId, EnApplyStatus statusValue);
12번 줄에 정의한 메서드는 @Query 어노테이션을 사용해서 직접 JPQL로 쿼리를 작성한 예시라서, 쿼리 안에 들어가는 :userId와 :statusValue를 파라미터로 전달하기 위해 @Param() 어노테이션을 붙입니다 !

하지만 15줄에서 정의한 메서드는 @Query로 직접 쿼리를 작성한게 아니라, 스프링 JPA에서 제공하는 쿼리 메서드를 사용해서 @Param() 어노테이션을 붙이지 않아도 됩니다.

복잡한 JPQL인 경우는 12줄처럼 직접 JPQL 작성하지만, 간단한 쿼리의 경우 쿼리 메서드를 주로 사용하기 때문에 여기서도 쿼리 메서드로 정의했습니다 :)

2024-02-03 09:23 UTC, yeseul106 commented on main/src/main/java/org/sopt/makers/crew/main/external/notification/PushNotificationServerClient.java
앗 !! 너무 좋아요 !!! 영우님 의견 너무 공감합니다 !! 해당 리뷰 반영하겠습니다 !

2024-02-03 09:23 UTC, yeseul106 commented on main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
> +  private static final String NEW_POST_PUSH_NOTIFICATION_TITLE = "✏️내 모임에 새로운 글이 업로드됐어요.";
역시... 그저 빛..✨ 좋은 피드백 감사합니다 ! Enum으로 정의해서 한 곳에서 관리하도록 리팩토링 하겠습니다 !!

2024-02-03 09:23 UTC, yeseul106 commented on main/src/main/java/org/sopt/makers/crew/main/post/v2/service/PostV2ServiceImpl.java
> +   * 모임 게시글 작성 - 모임에 속한 유저만 작성 가능 - 모임에 속한 유저가 아니면 403 에러
제가 또 nest.js꺼 냅다 긁어와버렸네요.. 하하 요것도 같이 수정해서 올리겠습니다 ~~~

2024-02-04 08:24 UTC, rdd9223 commented on main/src/main/java/org/sopt/makers/crew/main/entity/apply/ApplyRepository.java
> +  List<Apply> findAllByMeetingIdAndStatus(Integer meetingId, EnApplyStatus statusValue);
자세한 설명 감사합니다!!!

2024-02-05 16:06 UTC, rdd9223 approved these changes
잘 작성해주셔서 감사합니다!!

2024-02-06 13:03 UTC, merged