[#37] 피드 기능 구현
sopt-makers/sopt-crew-backend pull request #40
Opened 2023-09-15 07:20 UTC by yeseul106

## 👩‍💻 Contents

- 기존 작업된 내용 (feat. 영우쌤)
   - 모임 게시글 작성, 모임 게시글 조회, 모임 게시글 목록 조회, 모임 게시글 좋아요 토글, 모임 게시글 신고 api
   - 모임 게시글 댓글 목록 조회, 댓글 좋아요 토글, 댓글 작성, 댓글 신고 api
   
- 추가 작업 (feat. 예슬)
   - 모임 게시글 & 목록 조회 시, 유저가 좋아요를 눌렀는지 알려주는 로직을 구현했습니다.
   - 댓글 좋아요를 눌렀는지 알려주는 로직을 구현했습니다.
   - 모임 당 작성된 게시글 개수를 조회하는 api를 구현했습니다.
   - 게시글 작성 시, 기존 코드에는 해당 모임의 멤버가 아닐 때 403 에러를 던지도록 구현이 되어있는데 모임을 개설한 개설자도 403 에러가 던져져서, 이 부분을 수정했습니다.

## 📝 Review Note

- 원래 모임 게시글 & 목록 조회 시에는 `@AuthGuard` 로 jwt 토큰 검증을 하지 않아서 토큰 없이도 api 통신 가능하도록 구현이 되어 있었는데, 해당 유저가 좋아요를 눌렀는지 여부를 구하기 위해서는 userId를 토큰에서 꺼내야하기 때문에 `@AuthGuard`를 걸어줬습니다.

- 제 생각에는 크루 탭에서 보여지는 모든 정보들은 어짜피 로그인을 해야 보이기 때문에 토큰 검증이 다 있어야 한다고 생각해서 `@AuthGuard`를 걸어서 토큰 안에서 userId를 가져오는 것이 낫다고 생각했었는데요,,,! 해당 토큰 검증을 걸어주지 않았던 다른 이유가 있다면 쿼리로 userId를 받는 것도 괜찮을 것 같아서 이 부분에 대한 영우쌤 의견이 궁금합니다 ! 🧐

## 📣 Related Issue

- closed #37

2023-09-15 15:45 UTC, rdd9223 requested changes
고생하셨습니다!

2023-09-15 15:45 UTC, rdd9223 commented on server/src/comment/v1/comment-v1.service.ts
> +          });
이 부분을 고민해서 짜준 것 같은데, 이렇게 하면 1커멘트당 1 DB 접근이 필요해서 조회비용이 많이 들 것 같아요!
commentId들만 배열로 모아서 한번에 DB에 접근해서 commentIds에 대한 정보를 모두 가져와서 매핑하는 형태로 진행해보는건 어떨까요??

2023-09-15 15:45 UTC, rdd9223 commented on server/src/post/v1/post-v1.service.ts
> +    const postCount = await this.postRepository.count({
postCount의 조회에 실패했을 때의 예외처리도 필요할 것 같네요!

2023-09-15 15:45 UTC, rdd9223 commented on server/src/post/v1/post-v1.service.ts
> +
요부분도 위와 같은 의견입니다!

2023-09-15 15:48 UTC, rdd9223 commented
authguard를 설정해주지않은 일부부분은 #9 때문이었던 것 같아요. 확실히 이젠 auth를 해야할 것 같긴 해서 공홈팀에 무제한 토큰을 발급하든 해야겠네요..!

2023-09-17 06:19 UTC, rdd9223 commented
그리고 추가로 prettier가 안맞는 것 같은데... 확인 가능한가요?

2023-09-17 06:26 UTC, yeseul106 commented on server/src/comment/v1/comment-v1.service.ts
> +          });
아 넵 ! 맞네요 !! 역시 👍
요거 수정 하겠습니다. 감사합니다아 !

2023-09-17 08:40 UTC, yeseul106 commented on server/src/post/v1/post-v1.service.ts
> +    const postCount = await this.postRepository.count({
postCount의 조회 실패 케이스는 해당 meetingId를 가진 모임이 없을 때라고 생각했는데, 이 meetingId를 가진 모임이 있는지 없는지를 확인하려면 Meeting 테이블에 한번 더 접근해야 해서 쿼리비용 대비 중요도에 고민이 좀 있었습니다,,! 예외처 예외처리를 해주는게 낫겠죠 ???

2023-09-17 08:42 UTC, yeseul106 commented on server/src/post/v1/post-v1.service.ts
> +
넵 확인입니다 ! 빠르게 수정 후 다시 말씀 드리겠습니다 !

2023-09-17 08:44 UTC, yeseul106 commented
> authguard를 설정해주지않은 일부부분은 #9 때문이었던 것 같아요. 확실히 이젠 auth를 해야할 것 같긴 해서 공홈팀에 무제한 토큰을 발급하든 해야겠네요..!

아 넵 ! 해당 이슈 확인 했습니다 !

2023-09-17 08:50 UTC, yeseul106 commented
> 그리고 추가로 prettier가 안맞는 것 같은데... 확인 가능한가요?

아 ...! 제가 vscode 잘 안써서 세팅이 제대로 되어 있지가 않았네요 ㅜㅜ ! 요거까지 수정하겠습니다 !!

2023-09-17 11:19 UTC, rdd9223 commented on server/src/post/v1/post-v1.service.ts
> +    const postCount = await this.postRepository.count({
없는 meetingId를 넣어보니 0으로나와서 500케이스가 안나오긴 하네요! 그냥 진행해도 될 것 같습니다. 굿!

2023-09-17 11:27 UTC, rdd9223 commented on server/src/post/v1/post-v1.service.ts
> +    const isMeetingCreator = user.id === meeting.userId;
이부분이군요!! 감사합니다~!

2023-09-19 15:15 UTC, rdd9223 commented
최고최고!! 고생하셨습니다!!!

2023-09-21 02:27 UTC, merged